version: 2.1

jobs:
  alembic-upgrade:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: |
          cd pgsql
          pip install -r requirements.txt
          alembic upgrade head

workflows:
  Migrate Postgres:
    jobs:
      - alembic-upgrade:
          context:
            - postgres-creds-dev
