version: 2.1

orbs:
  helm: circleci/helm@1.2.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-eks: circleci/aws-eks@2.2.0

jobs:
  helm-upgrade:
    parameters:
      cluster-name:
        type: string
      aws-region:
        type: string
        default: us-east-2
      helm-values:
        type: string
      image-tag:
        type: string
        default: <<pipeline.git.revision>>
      chart:
        type: string
      release-name:
        type: string
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: <<parameters.cluster-name>>
          aws-region: <<parameters.aws-region>>
      - checkout
      - helm/upgrade-helm-chart:
          atomic: true
          chart: << parameters.chart >>
          helm-version: v3.6.0
          release-name: << parameters.release-name >>
          update-repositories: false
          values: <<parameters.helm-values>>
          values-to-override: tag=<<parameters.image-tag>>

workflows:
  Migrate Postgres:
    jobs:
      - aws-ecr/build-and-push-image:
          attach-workspace: true
          name: build-image
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          create-repo: true
          dockerfile: Dockerfile
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          path: 'pgsql'
          repo: migrate-pgsql-job
          tag: <<pipeline.git.revision>>,latest,<<pipeline.git.tag>>
          context:
            - aws-creds
          filters:
            branches:
              only:
                - main
      - helm-upgrade:
          release-name: migrate-pgsql-job
          chart: pgsql/helm
          cluster-name: dioptra-dev-eks
          helm-values: ./pgsql/helm/values.dev.yaml
          image-tag: <<pipeline.git.revision>>
          context:
            - aws-creds
          requires:
            - build-image
          filters:
            branches:
              only:
                - main
