"""added time_floor managed function

Created at: 2022-08-14 13:17:39.042051
"""

revision = '08c569b0772c'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '003af7aaaaa8'

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    public_time_floor = PGFunction(
        schema="public",
        signature="TIME_FLOOR(t timestamp with time zone, i interval)",
        definition="RETURNS timestamp with time zone AS \n        $$\n        BEGIN\n            RETURN date_bin(i, t, timestamptz '1970-01-01T00\\:00\\:00.000Z');\n        END; \n        $$ LANGUAGE plpgsql"
    )
    op.create_entity(public_time_floor)

    public_time_floor = PGFunction(
        schema="public",
        signature="time_floor(t timestamp with time zone, i interval)",
        definition="returns timestamp with time zone\n LANGUAGE plpgsql\nAS $function$\nBEGIN\n    RETURN date_bin(i, t, timestamp '2001-02-16 20\\:05\\:00');\nEND; $function$"
    )
    op.drop_entity(public_time_floor)

    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    public_time_floor = PGFunction(
        schema="public",
        signature="time_floor(t timestamp with time zone, i interval)",
        definition="returns timestamp with time zone\n LANGUAGE plpgsql\nAS $function$\nBEGIN\n    RETURN date_bin(i, t, timestamp '2001-02-16 20\\:05\\:00');\nEND; $function$"
    )
    op.create_entity(public_time_floor)

    public_time_floor = PGFunction(
        schema="public",
        signature="TIME_FLOOR(t timestamp with time zone, i interval)",
        definition="RETURNS timestamp with time zone AS \n        $$\n        BEGIN\n            RETURN date_bin(i, t, timestamptz '1970-01-01T00\\:00\\:00.000Z');\n        END; \n        $$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_time_floor)

    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass