"""added columns for image classification

Created at: 2022-08-11 13:13:33.055102
"""

revision = '174a8d87e0d1'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '4ee481ce0436'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('model_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('api_version', sa.String(), nullable=True))
    op.add_column('events', sa.Column('model_version', sa.String(), nullable=True))
    op.add_column('events', sa.Column('model_type', sa.String(), nullable=True))
    op.add_column('events', sa.Column('input_type', sa.String(), nullable=True))
    op.add_column('events', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('image_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('video_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('audio_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('text_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('groundtruth', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('embeddings', sa.String(), nullable=True))
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'embeddings')
    op.drop_column('events', 'confidence')
    op.drop_column('events', 'prediction')
    op.drop_column('events', 'groundtruth')
    op.drop_column('events', 'text_metadata')
    op.drop_column('events', 'audio_metadata')
    op.drop_column('events', 'video_metadata')
    op.drop_column('events', 'image_metadata')
    op.drop_column('events', 'features')
    op.drop_column('events', 'input_type')
    op.drop_column('events', 'model_type')
    op.drop_column('events', 'model_version')
    op.drop_column('events', 'api_version')
    op.drop_column('events', 'model_id')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass