"""Adds JSONB classifications to lanes

Created at: 2023-04-25 14:49:14.526780
"""

revision = '21b545c16403'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = 'f54f48148d17'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lanes', sa.Column('classifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('lanes', 'confidences')
    op.drop_column('lanes', 'class_names')
    op.drop_column('lanes', 'class_name')
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lanes', sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lanes', sa.Column('class_names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('lanes', sa.Column('confidences', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.drop_column('lanes', 'classifications')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass