"""Adds on delete cascade to tags, predictions, groundtruths

Created at: 2023-02-02 16:11:30.776157
"""

revision = '277a87675b1b'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = 'b71b034b816c'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_feature_vectors_datapoint_datapoints', 'feature_vectors', type_='foreignkey')
    op.drop_constraint('fk_feature_vectors_prediction_predictions', 'feature_vectors', type_='foreignkey')
    op.create_foreign_key(op.f('fk_feature_vectors_prediction_predictions'), 'feature_vectors', 'predictions', ['prediction'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_feature_vectors_datapoint_datapoints'), 'feature_vectors', 'datapoints', ['datapoint'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_groundtruths_datapoint_datapoints', 'groundtruths', type_='foreignkey')
    op.create_foreign_key(op.f('fk_groundtruths_datapoint_datapoints'), 'groundtruths', 'datapoints', ['datapoint'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_predictions_datapoint_datapoints', 'predictions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_predictions_datapoint_datapoints'), 'predictions', 'datapoints', ['datapoint'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_tags_datapoint_datapoints', 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tags_datapoint_datapoints'), 'tags', 'datapoints', ['datapoint'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tags_datapoint_datapoints'), 'tags', type_='foreignkey')
    op.create_foreign_key('fk_tags_datapoint_datapoints', 'tags', 'datapoints', ['datapoint'], ['id'])
    op.drop_constraint(op.f('fk_predictions_datapoint_datapoints'), 'predictions', type_='foreignkey')
    op.create_foreign_key('fk_predictions_datapoint_datapoints', 'predictions', 'datapoints', ['datapoint'], ['id'])
    op.drop_constraint(op.f('fk_groundtruths_datapoint_datapoints'), 'groundtruths', type_='foreignkey')
    op.create_foreign_key('fk_groundtruths_datapoint_datapoints', 'groundtruths', 'datapoints', ['datapoint'], ['id'])
    op.drop_constraint(op.f('fk_feature_vectors_datapoint_datapoints'), 'feature_vectors', type_='foreignkey')
    op.drop_constraint(op.f('fk_feature_vectors_prediction_predictions'), 'feature_vectors', type_='foreignkey')
    op.create_foreign_key('fk_feature_vectors_prediction_predictions', 'feature_vectors', 'predictions', ['prediction'], ['id'])
    op.create_foreign_key('fk_feature_vectors_datapoint_datapoints', 'feature_vectors', 'datapoints', ['datapoint'], ['id'])
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass