"""added timestamp and org_id indices

Created at: 2022-09-17 23:41:47.455050
"""

revision = '288f7f9295ef'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = 'b6765838fac2'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('events_organization_id_index', 'events', ['organization_id'], unique=False)
    op.create_index('events_timestamp_index', 'events', ['timestamp'], unique=False, postgresql_using='brin')
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('events_timestamp_index', table_name='events', postgresql_using='brin')
    op.drop_index('events_organization_id_index', table_name='events')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass