"""Adds constraints on bboxes

Created at: 2023-04-13 22:20:40.433753
"""

revision = '4447d779b3fb'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = 'bf2904dc3cef'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adds a check constraint 
    # CheckConstraint('(prediction IS NULL AND groundtruth IS NOT NULL) OR (prediction IS NOT NULL AND groundtruth IS NULL)', name='bboxes_prediction_xor_groundtruth_not_null')
    op.execute("""
        ALTER TABLE bboxes
        ADD CONSTRAINT bboxes_prediction_xor_groundtruth_not_null
        CHECK ((prediction IS NULL AND groundtruth IS NOT NULL) OR (prediction IS NOT NULL AND groundtruth IS NULL));
    """)
    # Adds a check constraint
    # CheckConstraint('NOT (groundtruth IS NOT NULL and confidence IS NOT NULL)', name='bboxes_groundtruth_confidence_null')
    op.execute("""
        ALTER TABLE bboxes
        ADD CONSTRAINT bboxes_groundtruth_confidence_null
        CHECK (NOT (groundtruth IS NOT NULL and confidence IS NOT NULL));
    """)

    # ### end Alembic commands ###

def schema_downgrades():
    # Remove constraints above
    op.execute("""
        ALTER TABLE bboxes
        DROP CONSTRAINT bboxes_prediction_xor_groundtruth_not_null;
    """)
    op.execute("""
        ALTER TABLE bboxes
        DROP CONSTRAINT bboxes_groundtruth_confidence_null;
    """)
    # #
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass