"""Adds Completions to TaskTypes

Created at: 2023-06-13 20:48:34.270279
"""

revision = '4d0e57a9565d'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '1a281948879c'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # Written manually
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE tasktype ADD VALUE 'COMPLETION'")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def schema_downgrades():
    # Written manually
    op.execute("ALTER TYPE tasktype RENAME TO tasktype_old")
    op.execute("CREATE TYPE tasktype AS ENUM('OBJECT_DETECTION', 'CLASSIFICATION'," 
               "'NER', 'INSTANCE_SEGMENTATION', 'SEMANTIC_SEGMENTATION' )")
    op.execute((
        "ALTER TABLE predictions ALTER COLUMN task_type TYPE tasktype USING "
        "task_type::text::tasktype"
    ))
    op.execute((
        "ALTER TABLE groundtruths ALTER COLUMN task_type TYPE tasktype USING "
        "task_type::text::tasktype"
    ))
    op.execute("DROP TYPE tasktype_old")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass