"""removes datapoints.request_id not null

Created at: 2023-02-05 15:01:41.882540
"""

revision = '61f3d7ccdd3c'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = 'fca972c72feb'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datapoints', 'request_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datapoints', 'request_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass