"""adds useful indexes

Created at: 2023-03-08 12:19:08.306665
"""

revision = '6dcac133421e'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = 'd94552f747f7'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('feature_vector_datapoint_index', 'feature_vectors', ['datapoint'], unique=False)
    op.create_index('feature_vector_model_name_index', 'feature_vectors', ['model_name'], unique=False)
    op.create_index('feature_vector_prediction_index', 'feature_vectors', ['prediction'], unique=False)
    op.create_index('feature_vector_type_index', 'feature_vectors', ['type'], unique=False)
    op.create_index('groundtruths_class_name_index', 'groundtruths', ['class_name'], unique=False)
    op.create_index('groundtruths_datapoint_index', 'groundtruths', ['datapoint'], unique=False)
    op.create_index('groundtruths_task_type_index', 'groundtruths', ['task_type'], unique=False)
    op.create_index('predictions_class_name_index', 'predictions', ['class_name'], unique=False)
    op.create_index('predictions_confidence_index', 'predictions', ['confidence'], unique=False)
    op.create_index('predictions_datapoint_index', 'predictions', ['datapoint'], unique=False)
    op.create_index('predictions_model_name_index', 'predictions', ['model_name'], unique=False)
    op.create_index('predictions_task_type_index', 'predictions', ['task_type'], unique=False)
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('predictions_task_type_index', table_name='predictions')
    op.drop_index('predictions_model_name_index', table_name='predictions')
    op.drop_index('predictions_datapoint_index', table_name='predictions')
    op.drop_index('predictions_confidence_index', table_name='predictions')
    op.drop_index('predictions_class_name_index', table_name='predictions')
    op.drop_index('groundtruths_task_type_index', table_name='groundtruths')
    op.drop_index('groundtruths_datapoint_index', table_name='groundtruths')
    op.drop_index('groundtruths_class_name_index', table_name='groundtruths')
    op.drop_index('feature_vector_type_index', table_name='feature_vectors')
    op.drop_index('feature_vector_prediction_index', table_name='feature_vectors')
    op.drop_index('feature_vector_model_name_index', table_name='feature_vectors')
    op.drop_index('feature_vector_datapoint_index', table_name='feature_vectors')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass