"""Added prompt_responses table

Created at: 2023-06-13 11:08:07.709023
"""

revision = '9654f44b69e8'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '21b545c16403'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_responses',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('prediction', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('groundtruth', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.CheckConstraint('groundtruth IS NULL OR groundtruth IS NOT NULL AND confidence IS NULL', name=op.f('ck_prompt_responses_`prompt_responses_groundtruth_confidence_null`')),
    sa.CheckConstraint('prediction IS NULL AND groundtruth IS NOT NULL OR prediction IS NOT NULL AND groundtruth IS NULL', name=op.f('ck_prompt_responses_`prompt_responses_prediction_xor_groundtruth_not_null`')),
    sa.ForeignKeyConstraint(['groundtruth'], ['groundtruths.id'], name=op.f('fk_prompt_responses_groundtruth_groundtruths'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction'], ['predictions.id'], name=op.f('fk_prompt_responses_prediction_predictions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_responses'))
    )
    op.create_index('prompt_responses_confidence_index', 'prompt_responses', ['confidence'], unique=False)
    op.create_index('prompt_responses_groundtruth_index', 'prompt_responses', ['groundtruth'], unique=False)
    op.create_index('prompt_responses_organization_id_index', 'prompt_responses', ['organization_id'], unique=False)
    op.create_index('prompt_responses_prediction_index', 'prompt_responses', ['prediction'], unique=False)
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('prompt_responses_prediction_index', table_name='prompt_responses')
    op.drop_index('prompt_responses_organization_id_index', table_name='prompt_responses')
    op.drop_index('prompt_responses_groundtruth_index', table_name='prompt_responses')
    op.drop_index('prompt_responses_confidence_index', table_name='prompt_responses')
    op.drop_table('prompt_responses')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass