"""adds segmentation to tasktypes

Find all custom enum types:
SELECT
    pg_type.typname, 
     pg_enum.enumlabel
FROM
    pg_type 
JOIN
    pg_enum ON pg_enum.enumtypid = pg_type.oid;

See https://makimo.pl/blog/upgrading-postgresqls-enum-type-with-sqlalchemy-using-alembic-migration/

Created at: 2023-03-08 14:39:38.272339
"""

revision = 'aa7eb351280c'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '6dcac133421e'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # Written manually
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE tasktype ADD VALUE 'SEGMENTATION'")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def schema_downgrades():
    # Written manually
    op.execute("ALTER TYPE tasktype RENAME TO tasktype_old")
    op.execute("CREATE TYPE tasktype AS ENUM('OBJECT_DETECTION', 'CLASSIFICATION', 'NER')")
    op.execute((
        "ALTER TABLE predictions ALTER COLUMN task_type TYPE tasktype USING "
        "task_type::text::tasktype"
    ))
    op.execute((
        "ALTER TABLE groundtruths ALTER COLUMN task_type TYPE tasktype USING "
        "task_type::text::tasktype"
    ))
    op.execute("DROP TYPE tasktype_old")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass