"""removed un encoded segmentation class mask from pred and gt and replace with resize list encoded

Created at: 2023-03-24 14:51:40.302611
"""

revision = 'b20dd50cf6f8'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '64c8cde6c4c8'

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groundtruths', sa.Column('encoded_resized_segmentation_class_mask', sa.String(), nullable=True))
    op.drop_column('groundtruths', 'segmentation_class_mask')
    op.add_column('predictions', sa.Column('encoded_resized_segmentation_class_mask', sa.String(), nullable=True))
    op.drop_column('predictions', 'segmentation_class_mask')
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('segmentation_class_mask', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('predictions', 'encoded_resized_segmentation_class_mask')
    op.add_column('groundtruths', sa.Column('segmentation_class_mask', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('groundtruths', 'encoded_resized_segmentation_class_mask')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass