"""Removed comitted column and renamed __time to timestamp

Created at: 2022-09-11 20:55:16.325505
"""

revision = 'b6765838fac2'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '74e80b5ef222'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'committed')
    op.alter_column('events', '__time', new_column_name='timestamp')
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'timestamp', new_column_name='__time')
    op.add_column('events', sa.Column('committed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass