"""fixes the feature vector unique type per model_name and datapoint

Created at: 2023-03-08 21:37:58.260291
"""

revision = 'bcdc54cb2650'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = 'aa7eb351280c'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set all feature_vectors.model_name columns to '' when they are NULL
    op.execute("UPDATE feature_vectors SET model_name = '' WHERE model_name IS NULL")
    op.alter_column('feature_vectors', 'model_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Set server default value of model_name to ''
    op.alter_column('feature_vectors', 'model_name', server_default='')
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feature_vectors', 'model_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass