"""added TIME_FLOOR function

Created at: 2022-08-11 19:40:14.419192
"""

revision = 'cdcaa2b94e58'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '89abf85c2edf'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    op.execute("""
CREATE OR REPLACE FUNCTION TIME_FLOOR(t timestamp with time zone, i interval)
RETURNS timestamp with time zone AS $$
BEGIN
    RETURN date_bin(i, t, timestamp '2001-02-16 20:05:00');
END; $$

LANGUAGE plpgsql;
    """)
    schema_upgrades()
    data_upgrades()

def downgrade():
    op.execute("""
DROP FUNCTION IF EXISTS TIME_FLOOR(t timestamp with time zone, i interval);
""")
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass