"""adds unique constraint on tags.name,tags.datapoint

Created at: 2023-02-01 14:55:10.561981
"""

revision = 'd2f23bfb8812'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '7f0b9466c642'

from alembic import op
import sqlalchemy as sa

from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tags_datapoint_name_unique', 'tags', ['datapoint', 'name'])
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_datapoint_name_unique', 'tags', type_='unique')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass