"""Adds class_names and confidences to lanes, GRAD_EMBEDDINGS to feature vector types

Created at: 2023-04-20 14:51:08.395204
"""

revision = 'dceae91e6530'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = '357e7d368099'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lanes', sa.Column('class_name', sa.String(), nullable=True))
    op.add_column('lanes', sa.Column('class_names', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('lanes', sa.Column('confidences', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###
    # Add GRAD_EMBEDDINGS as a value to featurevectortype type
    op.execute("ALTER TYPE featurevectortype ADD VALUE IF NOT EXISTS 'GRAD_EMBEDDINGS'")

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lanes', 'confidences')
    op.drop_column('lanes', 'class_names')
    op.drop_column('lanes', 'class_name')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass