"""Adds segmentation_class_masks and variances columns

Created at: 2023-03-09 15:26:11.683320
"""

revision = 'fa14c4bb73bc'
# To prune migrations prior to this one, set this down_revision to None
# and delete the files of the prior revisions.
down_revision = 'bcdc54cb2650'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groundtruths', sa.Column('segmentation_class_mask', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('predictions', sa.Column('variances', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('predictions', sa.Column('segmentation_class_mask', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'segmentation_class_mask')
    op.drop_column('predictions', 'variances')
    op.drop_column('groundtruths', 'segmentation_class_mask')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass